name: Build Localinator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            exe_name: Localinator-ubuntu
            hmm: ''
          - os: windows-latest
            exe_name: Localinator-windows
            hmm: '.exe'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Run packager script
        run: python packager.py

      - name: Create Executable
        run: |
          python -m pyinstaller --onefile --name "Localinator" --additional-hooks-dir=./hooks app.py

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.exe_name }}
          path: dist/Localinator${{ matrix.hmm }}

  datablob-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run packager script
        run: python packager.py

      - uses: actions/upload-artifact@v4
        with:
          name: Datablob
          path: packaged.py